site_name: pl_sql_interview
theme:
  name: material
  palette:
    - scheme: slate       # Light theme
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-night  # Dark mode icon
        name: Switch to dark mode
    - scheme: default         # Dark theme
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

# extra_css:
#       - extra.css

# extra_javascript:
#        - extra.js

#   palette:
#     scheme: default
#     primary: green
#     accent: indigo


  features:
    - navigation.tabs
    #- navigation.expand
    #- navigation.sections
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight

#
# PL_SQL\docs\Interview\1.Introduction.md

nav:
   
  - Introduction:
     - My_intro: Interview/1.Introduction.md

  - Sql:
      - sql_interview : Interview/2.sql.md
  - PL-SQL:
      - Plsql-Intro: Interview/3.pl_sql.md

          


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details