site_name: pl_sql_interview

theme:
  name: material
  palette:
    # Default: Dark theme
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Alternate: Light theme
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode

  features:
    - navigation.tabs
    # - navigation.expand
    # - navigation.sections
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight

extra_css:
  - styles/extra.css

extra_javascript:
  - extra.js

nav:
  - Introduction:
      - My_intro: Interview/1.Introduction.md

  - Sql:
      - sql_interview: Interview/2.sql.md

  - PL-SQL:
      - Plsql-Intro: Interview/3.plsql.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
